# SwiftLint Configuration for TermQ

included:
  - Sources

excluded:
  - .build
  - Package.swift

# Rule configuration
disabled_rules:
  - trailing_comma  # Allow trailing commas
  - line_length     # We'll use a custom rule below

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - yoda_condition

# Customizations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - r
    - g
    - b

type_name:
  min_length:
    warning: 3
    error: 0
  max_length:
    warning: 50
    error: 60

reporter: "xcode"
