import Foundation

/// Memory diagnostics report generated from Help → Memory Report….
///
/// Pure data, parsing and formatting. `MemoryReportCollector` fills a `Snapshot`;
/// this type turns it into the text users attach to an issue.
///
/// ## Privacy
///
/// The report holds only sizes, counts, terminal backends and object type names.
/// It never includes terminal output, card titles, paths, commands or environment
/// variables. Full `leaks` output is never kept because it can print the contents
/// of strings in memory — only its summary line and root type names survive
/// `leaksSummary(_:)`.
enum MemoryReport {
    struct SessionInfo: Sendable, Equatable {
        enum State: String, Sendable, CaseIterable {
            case openTab = "open tab"
            case closedTab = "closed tab, still in memory"
            case exited = "process exited"
        }

        let backend: String
        let state: State
        /// Lines above the visible screen plus the screen itself, for the active buffer.
        let approximateLines: Int
        let paneCount: Int
    }

    struct ToolSection: Sendable, Equatable {
        let title: String
        let body: String
    }

    struct Snapshot: Sendable {
        var generated: Date
        var appVersion: String
        var osVersion: String
        var physicalMemoryBytes: UInt64
        var processUptime: TimeInterval?
        var footprintBytes: UInt64?
        var peakFootprintBytes: UInt64?
        var liveCards: Int
        var deletedCards: Int
        var openTabs: Int
        var scrollbackSetting: Int
        var sessions: [SessionInfo]
        var tools: [ToolSection]
    }

    // MARK: - Rendering

    static func render(_ snapshot: Snapshot) -> String {
        var lines: [String] = [
            "TermQ Memory Report",
            String(repeating: "═", count: 40),
            "Generated:      \(ISO8601DateFormatter().string(from: snapshot.generated))",
            "App Version:    \(snapshot.appVersion)",
            "macOS:          \(snapshot.osVersion)",
            "Physical RAM:   \(formatBytes(snapshot.physicalMemoryBytes))",
            "Uptime:         \(snapshot.processUptime.map(formatDuration) ?? "unknown")",
            "Footprint:      \(snapshot.footprintBytes.map(formatBytes) ?? "unknown")",
            "Peak footprint: \(snapshot.peakFootprintBytes.map(formatBytes) ?? "unknown")",
        ]

        lines += section("Board (current workspace)")
        lines += [
            "Cards (live / deleted): \(snapshot.liveCards) / \(snapshot.deletedCards)",
            "Open tabs:              \(snapshot.openTabs)",
            "Scrollback setting:     \(snapshot.scrollbackSetting) lines",
        ]

        lines += section("Terminal sessions held in memory")
        lines.append(sessionCountsLine(snapshot.sessions))
        for (index, session) in snapshot.sessions.enumerated() {
            let panes = session.paneCount > 0 ? ", \(session.paneCount) panes" : ""
            lines.append(
                "  #\(index + 1) \(session.backend), \(session.state.rawValue), "
                    + "~\(session.approximateLines) lines\(panes)")
        }

        for tool in snapshot.tools {
            lines += section(tool.title)
            lines.append(tool.body)
        }

        lines += ["", String(repeating: "─", count: 40), "Generated by TermQ Help → Memory Report."]
        return lines.joined(separator: "\n")
    }

    /// One-line summary of how many sessions are in each state.
    static func sessionCountsLine(_ sessions: [SessionInfo]) -> String {
        let counts = SessionInfo.State.allCases.map { state in
            "\(sessions.filter { $0.state == state }.count) \(state.rawValue)"
        }
        return "Sessions: \(sessions.count) (\(counts.joined(separator: ", ")))"
    }

    private static func section(_ title: String) -> [String] {
        ["", "==== \(title) ===="]
    }

    // MARK: - Tool output parsing

    /// The header and category table from `footprint <pid>`.
    static func footprintExcerpt(_ output: String, maxLines: Int = 40) -> String {
        output.components(separatedBy: "\n").prefix(maxLines).joined(separator: "\n")
    }

    /// The totals line and the largest object types from `heap -sortBySize <pid>`.
    /// Type names only: `heap` never prints object contents in this mode.
    static func heapTopTypes(_ output: String, limit: Int = 30) -> String {
        var result: [String] = []
        var tableLinesLeft = -1
        for line in output.components(separatedBy: "\n") {
            if line.hasPrefix("All zones:") && line.hasSuffix("bytes)") {
                result.append(line)
            }
            if tableLinesLeft < 0, line.contains("COUNT"), line.contains("BYTES") {
                // Header and its "=====" underline, then `limit` rows.
                tableLinesLeft = limit + 2
            }
            if tableLinesLeft > 0 {
                result.append(line)
                tableLinesLeft -= 1
            }
        }
        return result.joined(separator: "\n")
    }

    /// The leak count and the number of leak roots per type from `leaks <pid>`.
    /// Everything else is dropped: full output can include string contents.
    static func leaksSummary(_ output: String, limit: Int = 15) -> String {
        let lines = output.components(separatedBy: "\n")
        let summary = lines.first { $0.contains("leaks for") && $0.contains("total leaked bytes") }

        var rootCounts: [String: Int] = [:]
        for line in lines {
            guard let range = line.range(of: #"ROOT (CYCLE|LEAK): <"#, options: .regularExpression)
            else { continue }
            let typeName = line[range.upperBound...].prefix { $0 != " " && $0 != ">" }
            guard !typeName.isEmpty else { continue }
            rootCounts[String(typeName), default: 0] += 1
        }

        var result = [summary ?? "No leak summary found."]
        if !rootCounts.isEmpty {
            result.append("Leak roots by type:")
            let sorted = rootCounts.sorted { $0.value != $1.value ? $0.value > $1.value : $0.key < $1.key }
            for (name, count) in sorted.prefix(limit) {
                result.append("  \(count)  \(name)")
            }
        }
        return result.joined(separator: "\n")
    }

    // MARK: - Redaction & formatting

    /// Replace the home directory and user name so reports can be shared.
    static func redact(_ text: String, home: String, user: String) -> String {
        var redacted = text
        if !home.isEmpty {
            redacted = redacted.replacingOccurrences(of: home, with: "~")
        }
        if !user.isEmpty {
            let pattern = #"\b"# + NSRegularExpression.escapedPattern(for: user) + #"\b"#
            redacted = redacted.replacingOccurrences(of: pattern, with: "USER", options: .regularExpression)
        }
        return redacted
    }

    /// Fixed-format byte size (MB with one decimal, GB above 10 GB) so reports
    /// read the same regardless of the user's locale.
    static func formatBytes(_ bytes: UInt64) -> String {
        let megabytes = Double(bytes) / 1_048_576
        if megabytes >= 10_240 {
            return String(format: "%.1f GB", megabytes / 1024)
        }
        return String(format: "%.1f MB", megabytes)
    }

    static func formatDuration(_ interval: TimeInterval) -> String {
        let totalMinutes = Int(interval) / 60
        let days = totalMinutes / 1440
        let hours = (totalMinutes % 1440) / 60
        let minutes = totalMinutes % 60
        return days > 0 ? "\(days)d \(hours)h \(minutes)m" : "\(hours)h \(minutes)m"
    }
}
